___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
pd.Series([2,3,6,5])

0    2
1    3
2    6
3    5
dtype: int64

In [3]:
ser = pd.Series([2,3,6,5])

In [4]:
ser

0    2
1    3
2    6
3    5
dtype: int64

### Basic Attributes of Series

In [5]:
type(ser)

pandas.core.series.Series

In [6]:
ser.dtype

dtype('int64')

In [7]:
ser.size

4

In [8]:
ser.ndim

1

In [9]:
ser.values

array([2, 3, 6, 5], dtype=int64)

In [10]:
for i in ser.values:
    print(i)

2
3
6
5


In [11]:
[i for i in ser.values]

[2, 3, 6, 5]

In [12]:
ser = pd.Series([2,3,5,6,8,9])

In [13]:
ser

0    2
1    3
2    5
3    6
4    8
5    9
dtype: int64

In [14]:
ser.head(6)

0    2
1    3
2    5
3    6
4    8
5    9
dtype: int64

In [15]:
ser.tail(2)

4    8
5    9
dtype: int64

In [16]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [17]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [18]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [19]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [20]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [21]:
pd.Series(data = arr, index = labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [22]:
d

{'a': 10, 'b': 20, 'c': 30}

In [23]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [24]:
pd.Series(data = d, index= ['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [26]:
set1 = {1,2,3,6}

In [27]:
pd.Series(set1)

TypeError: 'set' type is unordered

In [28]:
pd.Series(set)

0    <class 'set'>
dtype: object

In [29]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [30]:
mix_data = ['Aziz', 2, True]

In [31]:
pd.Series(mix_data)

0    Aziz
1       2
2    True
dtype: object

***



## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [32]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                      

In [33]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [34]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [35]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [36]:
ser1['Germany']

2

In [37]:
ser2['Japan']

4

Operations are then also done based off of index:

In [38]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [39]:
ser3 = pd.Series(data = labels)

ser3

0    a
1    b
2    c
dtype: object

In [40]:
ser3[0]

'a'

### Indexing Examples

In [41]:
a = np.array([1,2,33,444,75])
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [42]:
panser[0:1]

0    1
dtype: int32

### pandas_series[index] | pandas_series[[indices, indices...]]

In [43]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [44]:
panser['terry']

121

In [45]:
panser[2]

150

In [46]:
index1 = ['terry', 'micheal', 'jason']

In [47]:
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [48]:
panser['terry':'orion']

terry      121
micheal    200
orion      150
dtype: int64

In [49]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Several Selecting Attributes

In [50]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [51]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [52]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [53]:
panser.items()

In [54]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [55]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [56]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [57]:
'terry' in panser

True

In [58]:
'bob' in panser

False

In [59]:
121 in panser.values

True

In [60]:
55 in panser.values

False

In [61]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [62]:
panser['terry'] = 90

In [63]:
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [64]:
panser[panser < 100]

terry    90
jason    99
dtype: int64

In [65]:
panser[panser > 100]

micheal    200
orion      150
dtype: int64

# The End of the Session - 3

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas DataFrames, Session - 3</p><h1>

In [67]:
data = [1, 2, 39, 67, 90]

In [68]:
data

[1, 2, 39, 67, 90]

In [69]:
pd.DataFrame(data, columns=['column1'])

column1
0        1
1        2
2       39
3       67
4       90

In [70]:
data2 = np.arange(1,10).reshape(3,3)

In [71]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
pd.DataFrame(data2, columns=['var1', 'var2', 'var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [73]:
data3 = np.arange(1,21).reshape(10,2)

In [74]:
df3 = pd.DataFrame(data3, columns=['var1', 'var2'])

In [75]:
df3.head()

var1  var2
0     1     2
1     3     4
2     5     6
3     7     8
4     9    10

In [76]:
df3.tail(3)

var1  var2
7    15    16
8    17    18
9    19    20

In [77]:
df3.columns

Index(['var1', 'var2'], dtype='object')

In [78]:
for i in df3.columns:
    print(i)

var1
var2


In [79]:
df3.columns = ['new1', 'new2']

In [80]:
df3

new1  new2
0     1     2
1     3     4
2     5     6
3     7     8
4     9    10
5    11    12
6    13    14
7    15    16
8    17    18
9    19    20

In [81]:
type(df3)

pandas.core.frame.DataFrame

In [82]:
df3.shape

(10, 2)

In [83]:
df3.ndim

2

In [84]:
df3.size

20

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor