```
This problem was asked by Facebook.
Given an N by N matrix, rotate it by 90 degrees clockwise.
For example, given the following matrix:
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
you should return:
[[7, 4, 1],
 [8, 5, 2],
 [9, 6, 3]]
```




In [10]:
def rotate(a): 
  return [list(i) for i in list(zip(*a[::-1]))]
rotate([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]

In [11]:
import numpy as np
def rotate(x):
    return np.array(x[::-1]).T
comolokko([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

[[7 4 1]
 [8 5 2]
 [9 6 3]]
